import { NgModule }             from '@angular/core';
import { CommonModule }         from '@angular/common';
import { HttpModule }           from '@angular/http';
import { FormsModule, ReactiveFormsModule }     from '@angular/forms';
import { MyFormsModule }        from '../forms/myForms.module';
import { CdkTableModule } from '@angular/cdk/table';
import {
  MatAutocompleteModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  MatChipsModule,
  MatDatepickerModule,
  MatDialogModule,
  MatDividerModule,
  MatExpansionModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatNativeDateModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatRadioModule,
  MatRippleModule,
  MatSelectModule,
  MatSidenavModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatSnackBarModule,
  MatSortModule,
  MatStepperModule,
  MatTableModule,
  MatTabsModule,
  MatToolbarModule,
  MatTooltipModule,
} from '@angular/material';

import { MapComponent } from './map/map.component';

@NgModule({
  imports:      [ CommonModule ],
  declarations: [ MapComponent ],
  exports:      [ MapComponent, CommonModule, FormsModule, ReactiveFormsModule, HttpModule, MyFormsModule, 
                  CdkTableModule,
                  MatAutocompleteModule,
                  MatButtonModule,
                  MatButtonToggleModule,
                  MatCardModule,
                  MatCheckboxModule,
                  MatChipsModule,
                  MatStepperModule,
                  MatDatepickerModule,
                  MatDialogModule,
                  MatDividerModule,
                  MatExpansionModule,
                  MatGridListModule,
                  MatIconModule,
                  MatInputModule,
                  MatListModule,
                  MatMenuModule,
                  MatNativeDateModule,
                  MatPaginatorModule,
                  MatProgressBarModule,
                  MatProgressSpinnerModule,
                  MatRadioModule,
                  MatRippleModule,
                  MatSelectModule,
                  MatSidenavModule,
                  MatSliderModule,
                  MatSlideToggleModule,
                  MatSnackBarModule,
                  MatSortModule,
                  MatTableModule,
                  MatTabsModule,
                  MatToolbarModule,
                  MatTooltipModule,]
})
export class SharedModule { }