CREATE TABLE IF NOT EXISTS users(ID BINARY(16) PRIMARY KEY, userName VARCHAR(30), firstName VARCHAR(30), lastName VARCHAR(30), password VARCHAR(30));

CREATE TABLE IF NOT EXISTS user(ID BIGINT PRIMARY KEY, userName VARCHAR(100), password VARCHAR(100), firstName VARCHAR(100), lastName VARCHAR(100), email VARCHAR(30),  enabled boolean, LASTPASSWORDRESETDATE timestamp);

CREATE TABLE IF NOT EXISTS AUTHORITY(ID BIGINT PRIMARY KEY, Name VARCHAR(100));

CREATE TABLE IF NOT EXISTS USER_AUTHORITY(USER_ID BIGINT, FOREIGN KEY (USER_ID) REFERENCES public.user(ID), AUTHORITY_ID VARCHAR(100), FOREIGN KEY (AUTHORITY_ID) REFERENCES public.AUTHORITY(ID));

